apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs
  namespace: flux-system
spec:
  interval: 5m
  path: ./infrastructure/configs/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: orion-staging
  dependsOn:
    - name: infra-controllers

